### ISSUE TITLE
handler-mailer-mailgun Gem dependency error

### ISSUE THREAD

**Issue by pmualaba** [sensu-plugins/sensu-plugins-mailer#10] opened 2015-12-30 20:47 UTC
Hello,
If I use handler-mailer then everything works fine, 

{"timestamp":"2015-12-30T21:33:20.861799+0100","level":"info","message":"handler output","handler":{"type":"pipe","command":"ruby /opt/sensu/embedded/bin/handler-mailer.rb","name":"default"},"output":["only handling every 180 occurrences: nanoweb.be/disk\n"]}
{"timestamp":"2015-12-30T21:33:23.124780+0100","level":"info","message":"handler output","handler":{"type":"pipe","command":"ruby /opt/sensu/embedded/bin/handler-mailer.rb","name":"default"},"output":["mail -- sent alert for mona.nanocloud.be/disk to patrick.mualaba@gmail.com\n"]}
{"timestamp":"2015-12-30T21:33:29.288313+0100","level":"info","message":"publishing check request","payload":{"name":"disk","issued":1451507609,"command":"exit 2"},"subscribers":["test"]}

but when i switch to handler-mailer-mailgun I get following error:

{"timestamp":"2015-12-30T18:33:20.018312+0100","level":"info","message":"handler output","handler":{"type":"pipe","command":"/opt/sensu/embedded/bin/handler-mailer-mailgun.rb","name":"default"},"output":["/opt/sensu/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- mailgun-ruby (LoadError)\n\tfrom /opt/sensu/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugins-mailer-0.1.1/bin/handler-mailer-mailgun.rb:32:in `<top (required)>'\n\tfrom /opt/sensu/embedded/bin/handler-mailer-mailgun.rb:23:in `load'\n\tfrom /opt/sensu/embedded/bin/handler-mailer-mailgun.rb:23:in `<main>'\nonly handling every 180 occurrences: nanoweb.be/disk\n"]}

**Comment by eheydrick** [comment] 2015-12-30 21:25
The problem is the gem require is wrong (https://github.com/sensu-plugins/sensu-plugins-mailer/blob/master/bin/handler-mailer-mailgun.rb#L32) should be `require 'mailgun'`. I just pushed a fix in version 0.1.2. Can you give that a try.

**Comment by pmualaba** [comment] 2015-12-30 21:45
Great! Works now. Thanks for speedy solution!

**Closed** 2016-01-01 01:47 UTC
